# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeti-alpha" do
  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :big_sur

  version "0.10.2-alpha.20261002.76.1"

  on_macos do
    app "Yeti Alpha.app"
  end

  on_macos do
    on_arm do
      sha256 "12d49ef103eaf7f72cd285839329e0e2dec8763525e1efeabd55337666c3bc94"
      url "https://yeti-releases.s3.eu-west-1.amazonaws.com/alpha/v#{version}/Yeti-Alpha_#{version}_aarch64.dmg"
    end
  end

  name "yeti-alpha"
  desc "Fast, local-first desktop client for YouTrack"
  homepage "https://github.com/JetBrains/yeti"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Yeti Alpha.app"]
  end

  zap trash: [
      "~/Library/Application Support/app.yeti.desktop.alpha",
      "~/Library/Logs/app.yeti.desktop.alpha",
    ]

end
