# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeti-alpha" do
  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :monterey
  # Homebrew expands appdir at install time.
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Yeti Alpha.app"]
  end

  version "0.11.1-alpha.20261008.90.1"

  on_macos do
    app "Yeti Alpha.app"
  end

  on_macos do
    on_arm do
      sha256 "68caee8a3aefcd91aef8f04a4e3d25d92fb5d71439647888e5575e2ba134cdc4"
      url "https://yeti-releases.s3.eu-west-1.amazonaws.com/alpha/v#{version}/Yeti-Alpha_#{version}_aarch64.dmg"
    end
  end

  name "yeti-alpha"
  desc "Fast, local-first desktop client for YouTrack"
  homepage "https://github.com/JetBrains/yeti"

  livecheck do
    skip "Auto-generated on release."
  end

  zap trash: [
      "~/Library/Application Support/app.yeti.desktop.alpha",
      "~/Library/Logs/app.yeti.desktop.alpha",
    ]

end
