# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeti" do
  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :big_sur

  version "0.10.0"

  on_macos do
    app "Yeti.app"
  end

  on_macos do
    on_arm do
      sha256 "0d88c43386964e494a19351ce7163eea523029004256a5dd7794a0c1121976c1"
      url "https://yeti-releases.s3.eu-west-1.amazonaws.com/v#{version}/Yeti_#{version}_aarch64.dmg"
    end
  end

  name "yeti"
  desc "Fast, local-first desktop client for YouTrack"
  homepage "https://github.com/JetBrains/yeti"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Yeti.app"]
  end

  zap trash: [
      "~/Library/Application Support/app.yeti.desktop",
      "~/Library/Logs/app.yeti.desktop",
    ]

end
