# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termbook < Formula
  desc "Beautiful, browsable reference pages for your CLI"
  homepage "https://github.com/tiulpin/termbook"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiulpin/termbook/releases/download/v0.2.0/termbook_0.2.0_macos_x86_64.tar.gz"
      sha256 "bfa4d53f220d7876f9de400226ec47deda199cc3cdc91123625cc4442d3b8e3f"

      define_method(:install) do
        bin.install "termbook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiulpin/termbook/releases/download/v0.2.0/termbook_0.2.0_macos_arm64.tar.gz"
      sha256 "cd02f7b38bc9453debb83e5ad30426adbc8fb9baedfeab98a0bdcd4fc296c97b"

      define_method(:install) do
        bin.install "termbook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiulpin/termbook/releases/download/v0.2.0/termbook_0.2.0_linux_x86_64.tar.gz"
      sha256 "bc750bd7dadc25adefa57f55401493a0bfd874ecdd8acaab9154af92260de7b1"
      define_method(:install) do
        bin.install "termbook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiulpin/termbook/releases/download/v0.2.0/termbook_0.2.0_linux_arm64.tar.gz"
      sha256 "aa99ba1fcd0f3a333f09c99f54b09a2bf8a9b80b6265ed1d4be792836b163dde"
      define_method(:install) do
        bin.install "termbook"
      end
    end
  end

  test do
    assert_match "termbook", shell_output("#{bin}/termbook --version")
  end
end
