# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termbook < Formula
  desc "Beautiful, browsable reference pages for your CLI"
  homepage "https://github.com/tiulpin/termbook"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiulpin/termbook/releases/download/v0.3.0/termbook_0.3.0_macos_x86_64.tar.gz"
      sha256 "08466951fdf75918a2cc6503ced457a985dfd1b395b32237c72d09a8f5ff9884"

      define_method(:install) do
        bin.install "termbook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiulpin/termbook/releases/download/v0.3.0/termbook_0.3.0_macos_arm64.tar.gz"
      sha256 "eb31f4d7acba4a92b1a09faa8ceb576df6edd3a4daebb3db428b354fd1cbb7c2"

      define_method(:install) do
        bin.install "termbook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiulpin/termbook/releases/download/v0.3.0/termbook_0.3.0_linux_x86_64.tar.gz"
      sha256 "f7867aa3c9218c922306d31ee18c8875ad53d97f4fbdbafc75824140de34251a"
      define_method(:install) do
        bin.install "termbook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiulpin/termbook/releases/download/v0.3.0/termbook_0.3.0_linux_arm64.tar.gz"
      sha256 "3b914ac57144075e38f90c415ebe9bf457511b03840d4a50f1175c98c57e821c"
      define_method(:install) do
        bin.install "termbook"
      end
    end
  end

  test do
    assert_match "termbook", shell_output("#{bin}/termbook --version")
  end
end
